var patientsArray = [{"id":1,"firstName":"Jevy","lastName":"Wang","DOB":"24/02/1987"},
{"id":2,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":3,"firstName":"Aaron","lastName":"Richard","DOB":"04/08/1990"},
{"id":4,"firstName":"Bob","lastName":"Wood","DOB":"07/07/1982"},
{"id":5,"firstName":"Colin","lastName":"Churchill","DOB":"11/07/1970"},
{"id":6,"firstName":"Hale","lastName":"Black","DOB":"04/08/1999"},
{"id":7,"firstName":"Ellis","lastName":"Brown","DOB":"23/07/1997"},
// {"id":8,"firstName":"Ford","lastName":"Baker","DOB":"04/10/1954"},
// {"id":9,"firstName":"Abel","lastName":"Franklin","DOB":"04/12/1987"},
// {"id":10,"firstName":"Jerry","lastName":"Smith","DOB":"03/09/1986"},
// {"id":11,"firstName":"Bill","lastName":"Smith","DOB":"06/07/1988"},
// {"id":12,"firstName":"Jack","lastName":"Johnson","DOB":"09/06/1999"},
// {"id":13,"firstName":"Barry","lastName":"Jone","DOB":"04/06/2000"},
// {"id":14,"firstName":"David","lastName":"Williams","DOB":"04/02/1979"},
// {"id":15,"firstName":"Bill","lastName":"Williams","DOB":"11/01/1981"},
// {"id":16,"firstName":"Harlan","lastName":"Martinson","DOB":"30/07/1985"},
// {"id":17,"firstName":"Dick","lastName":"Franklin","DOB":"29/07/1988"},
// {"id":18,"firstName":"Felix","lastName":"Franklin","DOB":"04/05/1987"},
{"id":19,"firstName":"Harry","lastName":"Miller","DOB":"15/02/2003"},
{"id":20,"firstName":"Eric","lastName":"Cook","DOB":"11/07/1992"}];


var notesArray =
[
 {"1":[{"nid":"1","doctor":"Jason","time":"04/09/2007","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" },{"nid":"2","doctor":"Andy","time":"04/07/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"2":[{"nid":"1","doctor":"Bob","time":"02/05/2005","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"3":[{"nid":"1","doctor":"Jason","time":"02/08/2015","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" },{"nid":"2","doctor":"Eric","time":"04/07/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"4":[{"nid":"1","doctor":"Jason","time":"06/05/2011","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"5":[{"nid":"1","doctor":"Andy","time":"02/05/2012","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"6":[{"nid":"1","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"7":[{"nid":"1","doctor":"Bob","time":"11/05/2012","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
//  {"8":[{"nid":"1","doctor":"Bob","time":"02/05/2001","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
//  {"9":[{"nid":"1","doctor":"Jason","time":"02/05/2002","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"10":[{"nid":"1","doctor":"Jason","time":"23/04/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"11":[{"nid":"1","doctor":"Andy","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"12":[{"nid":"1","doctor":"Jason","time":"02/03/2005","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"13":[{"nid":"1","doctor":"Vic","time":"24/02/2002","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"14":[{"nid":"1","doctor":"Vic","time":"23/05/2011","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"15":[{"nid":"1","doctor":"Jason","time":"02/11/2013","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"16":[{"nid":"1","doctor":"Vic","time":"11/05/2012","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"17":[{"nid":"1","doctor":"Jason","time":"02/12/2011","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
// {"18":[{"nid":"1","doctor":"Stan","time":"13/05/2011","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"19":[{"nid":"1","doctor":"Jason","time":"18/03/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"20":[{"nid":"1","doctor":"Stan","time":"07/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]}];
