var patientsArray = [{"id":1,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":2,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":3,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":4,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":5,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":6,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":7,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":8,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":9,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":10,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":11,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":12,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":13,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":14,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":15,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":16,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":17,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":18,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":19,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"},
{"id":20,"firstName":"Tomas","lastName":"Franklin","DOB":"04/07/1987"}];


var notesArray =
[
 {"1":[{"nid":"1", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"2":[{"nid":"2", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"3":[{"nid":"3", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"4":[{"nid":"4", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"5":[{"nid":"5", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"6":[{"nid":"6", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"7":[{"nid":"7", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"8":[{"nid":"8", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
 {"9":[{"nid":"9", "doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"10":[{"nid":"10","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"11":[{"nid":"11","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"12":[{"nid":"12","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"13":[{"nid":"13","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"14":[{"nid":"14","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"15":[{"nid":"15","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"16":[{"nid":"16","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"17":[{"nid":"17","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"18":[{"nid":"18","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"19":[{"nid":"19","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]},
{"20":[{"nid":"20","doctor":"Jason","time":"02/05/2009","note":"Test Note for patient, Test Note for patient, Doctor displays on right-above, Click right-above 'X' to delete a note" }]}];
